// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::all)]
pub struct OperationRegistry<B, Op0, In0, Op1, In1> {
    healthcheck: Op0,
    register_service: Op1,
    _phantom: std::marker::PhantomData<(B, In0, In1)>,
}
#[allow(clippy::all)]
pub struct OperationRegistryBuilder<B, Op0, In0, Op1, In1> {
    healthcheck: Option<Op0>,
    register_service: Option<Op1>,
    _phantom: std::marker::PhantomData<(B, In0, In1)>,
}
#[derive(std::fmt::Debug)]
pub enum OperationRegistryBuilderError {
    UninitializedField(&'static str),
}
impl std::fmt::Display for OperationRegistryBuilderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UninitializedField(v) => write!(f, "{}", v),
        }
    }
}
impl std::error::Error for OperationRegistryBuilderError {}
impl<B, Op0, In0, Op1, In1> Default for OperationRegistryBuilder<B, Op0, In0, Op1, In1> {
    fn default() -> Self {
        Self {
            healthcheck: Default::default(),
            register_service: Default::default(),
            _phantom: std::marker::PhantomData,
        }
    }
}
#[allow(clippy::all)]
impl<B, Op0, In0, Op1, In1> OperationRegistryBuilder<B, Op0, In0, Op1, In1> {
    pub fn healthcheck(self, value: Op0) -> Self {
        let mut new = self;
        new.healthcheck = Some(value);
        new
    }
    pub fn register_service(self, value: Op1) -> Self {
        let mut new = self;
        new.register_service = Some(value);
        new
    }
    pub fn build(
        self,
    ) -> Result<OperationRegistry<B, Op0, In0, Op1, In1>, OperationRegistryBuilderError> {
        Ok(OperationRegistry {
            healthcheck: match self.healthcheck {
                Some(v) => v,
                None => {
                    return Err(OperationRegistryBuilderError::UninitializedField(
                        "healthcheck",
                    ))
                }
            },
            register_service: match self.register_service {
                Some(v) => v,
                None => {
                    return Err(OperationRegistryBuilderError::UninitializedField(
                        "register_service",
                    ))
                }
            },
            _phantom: std::marker::PhantomData,
        })
    }
}
#[allow(clippy::all)]
impl<B, Op0, In0, Op1, In1> From<OperationRegistry<B, Op0, In0, Op1, In1>>
    for aws_smithy_http_server::routing::Router<B>
where
    B: Send + 'static,
    Op0: crate::operation_handler::Handler<B, In0, crate::input::HealthcheckInput>,
    In0: 'static,
    Op1: crate::operation_handler::Handler<B, In1, crate::input::RegisterServiceInput>,
    In1: 'static,
{
    fn from(registry: OperationRegistry<B, Op0, In0, Op1, In1>) -> Self {
        let healthcheck_request_spec = aws_smithy_http_server::routing::request_spec::RequestSpec::new(
            http::Method::GET,
            aws_smithy_http_server::routing::request_spec::UriSpec {
                host_prefix: None,
                path_and_query: aws_smithy_http_server::routing::request_spec::PathAndQuerySpec {
                    path_segments: aws_smithy_http_server::routing::request_spec::PathSpec::from_vector_unchecked(vec![aws_smithy_http_server::routing::request_spec::PathSegment::Literal(String::from("healthcheck"))]),
                    query_segments: aws_smithy_http_server::routing::request_spec::QuerySpec::from_vector_unchecked(vec![])
                }
            }
        );
        let register_service_request_spec = aws_smithy_http_server::routing::request_spec::RequestSpec::new(
            http::Method::PUT,
            aws_smithy_http_server::routing::request_spec::UriSpec {
                host_prefix: None,
                path_and_query: aws_smithy_http_server::routing::request_spec::PathAndQuerySpec {
                    path_segments: aws_smithy_http_server::routing::request_spec::PathSpec::from_vector_unchecked(vec![aws_smithy_http_server::routing::request_spec::PathSegment::Literal(String::from("service")), aws_smithy_http_server::routing::request_spec::PathSegment::Label]),
                    query_segments: aws_smithy_http_server::routing::request_spec::QuerySpec::from_vector_unchecked(vec![])
                }
            }
        );
        aws_smithy_http_server::routing::Router::new()
            .route(
                healthcheck_request_spec,
                crate::operation_handler::operation(registry.healthcheck),
            )
            .route(
                register_service_request_spec,
                crate::operation_handler::operation(registry.register_service),
            )
    }
}
